# Generated by Django 2.1.15 on 2022-02-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('direction', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=250, unique=True)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
