# Generated by Django 2.1.15 on 2022-02-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='direction',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefono',
            new_name='phone',
        ),
    ]
