# Generated by Django 2.1.15 on 2022-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20220205_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=250),
        ),
    ]
