# Generated by Django 2.1.15 on 2022-02-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20220205_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
